export const US_STATES = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
];

export const DEGREES = ["MD", "PhD", "MSW", "LCSW", "PsyD"];

export const SPECIALTIES = [
  { value: "Bipolar", label: "Bipolar" },
  { value: "LGBTQ", label: "LGBTQ" },
  { value: "Medication/Prescribing", label: "Medication/Prescribing" },
  { value: "Suicide History/Attempts", label: "Suicide History/Attempts" },
  { value: "General Mental Health (anxiety, depression, stress, grief, life transitions)", label: "General Mental Health" },
  { value: "Men's issues", label: "Men's issues" },
  { value: "Relationship Issues (family, friends, couple, etc)", label: "Relationship Issues" },
  { value: "Trauma & PTSD", label: "Trauma & PTSD" },
  { value: "Personality disorders", label: "Personality disorders" },
  { value: "Personal growth", label: "Personal growth" },
  { value: "Substance use/abuse", label: "Substance use/abuse" },
  { value: "Pediatrics", label: "Pediatrics" },
  { value: "Women's issues (post-partum, infertility, family planning)", label: "Women's issues" },
  { value: "Chronic pain", label: "Chronic pain" },
  { value: "Weight loss & nutrition", label: "Weight loss & nutrition" },
  { value: "Eating disorders", label: "Eating disorders" },
  { value: "Diabetic Diet and nutrition", label: "Diabetic Diet and nutrition" },
  { value: "Coaching (leadership, career, academic and wellness)", label: "Coaching" },
  { value: "Life coaching", label: "Life coaching" },
  { value: "Obsessive-compulsive disorders", label: "OCD" },
  { value: "Neuropsychological evaluations & testing (ADHD testing)", label: "Neuropsych Testing" },
  { value: "Attention and Hyperactivity (ADHD)", label: "ADHD" },
  { value: "Sleep issues", label: "Sleep issues" },
  { value: "Schizophrenia and psychotic disorders", label: "Schizophrenia" },
  { value: "Learning disorders", label: "Learning disorders" },
  { value: "Domestic abuse", label: "Domestic abuse" },
];
